insert into Countries ([Name]) values ('Azerbaijan'); 
insert into Countries ([Name]) values ('Ukraine'); 
insert into Countries ([Name]) values ('Russian');  


insert into Cities ([Name]) values ('Baku');
insert into Cities ([Name]) values ('Gence');
insert into Cities ([Name]) values ('Kiev');
insert into Cities ([Name]) values ('Odessa');
insert into Cities ([Name]) values ('Moscow');
insert into Cities ([Name]) values ('Sankt-Piterburg'); 
 

insert into Categories ([Name]) values ('Spectacle');
insert into Categories ([Name]) values ('Concert');
insert into Categories ([Name]) values ('Exhibition');
insert into Categories ([Name]) values ('The circus');
insert into Categories ([Name]) values ('Sport');
insert into Categories ([Name]) values ('Seminars and trainings');
insert into Categories ([Name]) values ('Movie');
insert into Categories ([Name]) values ('Humor'); 
insert into Categories ([Name]) values ('Party');
insert into Categories ([Name]) values ('For children');
insert into Categories ([Name]) values ('Other'); 
 

insert into Providences (CountriyId, CityId, Street) values (3, 2, '5 Scofield Drive');
insert into Providences (CountriyId, CityId, Street) values (1, 6, '407 Onsgard Street');
insert into Providences (CountriyId, CityId, Street) values (3, 3, '1606 Canary Terrace');
insert into Providences (CountriyId, CityId, Street) values (3, 1, '1 Montana Terrace');
insert into Providences (CountriyId, CityId, Street) values (1, 4, '782 Calypso Street');
insert into Providences (CountriyId, CityId, Street) values (2, 6, '08 Carey Circle');
insert into Providences (CountriyId, CityId, Street) values (2, 6, '47 Bay Street');
insert into Providences (CountriyId, CityId, Street) values (1, 4, '02 Coolidge Way');
insert into Providences (CountriyId, CityId, Street) values (2, 2, '40 Holy Cross Pass');
insert into Providences (CountriyId, CityId, Street) values (1, 1, '4 Karstens Street');


insert into Clients (FullName, Email, YearOfBirth) values ('Xever Stenyng', 'xstenyng0@bbb.org', '1970-08-02');
insert into Clients (FullName, Email, YearOfBirth) values ('Una Dallaway', 'udallaway1@dailymail.co.uk', '1972-11-16');
insert into Clients (FullName, Email, YearOfBirth) values ('Murielle Pipet', 'mpipet2@cyberchimps.com', '1997-07-04');
insert into Clients (FullName, Email, YearOfBirth) values ('Barney Sirmon', 'bsirmon3@twitpic.com', '1973-03-14');
insert into Clients (FullName, Email, YearOfBirth) values ('Marthe Sawkin', 'msawkin4@histats.com', '1998-03-11');
insert into Clients (FullName, Email, YearOfBirth) values ('Bern Leghorn', 'bleghorn5@tinypic.com', '1970-10-13');
insert into Clients (FullName, Email, YearOfBirth) values ('Ike O''Hare', 'iohare6@utexas.edu', '1988-05-19');
insert into Clients (FullName, Email, YearOfBirth) values ('Valeda Jane', 'vjane7@bloglines.com', '1999-05-26');
insert into Clients (FullName, Email, YearOfBirth) values ('Clementine Simecek', 'csimecek8@mashable.com', '1977-12-14');
insert into Clients (FullName, Email, YearOfBirth) values ('Donica Naish', 'dnaish9@google.pl', '1973-05-11');
insert into Clients (FullName, Email, YearOfBirth) values ('Ronald Breffit', 'rbreffita@github.io', '1977-09-17');
insert into Clients (FullName, Email, YearOfBirth) values ('Christabel Winborn', 'cwinbornb@dmoz.org', '1997-06-03');
insert into Clients (FullName, Email, YearOfBirth) values ('Truman Manlow', 'tmanlowc@thetimes.co.uk', '1990-03-29');
insert into Clients (FullName, Email, YearOfBirth) values ('Grazia Doddemeede', 'gdoddemeeded@senate.gov', '1990-12-31');
insert into Clients (FullName, Email, YearOfBirth) values ('Norman Beebe', 'nbeebee@bloglines.com', '1971-11-01');
insert into Clients (FullName, Email, YearOfBirth) values ('Lilla Pease', 'lpeasef@mayoclinic.com', '1995-05-03');
insert into Clients (FullName, Email, YearOfBirth) values ('Derrik Dulton', 'ddultong@chronoengine.com', '1976-08-26');
insert into Clients (FullName, Email, YearOfBirth) values ('Ruperta Deluca', 'rdelucah@nhs.uk', '1992-11-12');
insert into Clients (FullName, Email, YearOfBirth) values ('Berkley Gogay', 'bgogayi@army.mil', '1972-11-22');
insert into Clients (FullName, Email, YearOfBirth) values ('Elbertina Kolinsky', 'ekolinskyj@studiopress.com', '1989-01-04');
insert into Clients (FullName, Email, YearOfBirth) values ('Mercy Finey', 'mfineyk@slate.com', '1997-08-04');
insert into Clients (FullName, Email, YearOfBirth) values ('Brooke Claige', 'bclaigel@economist.com', '1979-06-25');
insert into Clients (FullName, Email, YearOfBirth) values ('Annecorinne Bamlett', 'abamlettm@wikimedia.org', '1969-09-19');
insert into Clients (FullName, Email, YearOfBirth) values ('Nikolia Atte-Stone', 'nattestonen@printfriendly.com', '1981-08-11');
insert into Clients (FullName, Email, YearOfBirth) values ('Engelbert Kull', 'ekullo@state.gov', '1982-08-23');
insert into Clients (FullName, Email, YearOfBirth) values ('Lenka Cornell', 'lcornellp@oaic.gov.au', '1975-03-21');
insert into Clients (FullName, Email, YearOfBirth) values ('Kristian Baudts', 'kbaudtsq@upenn.edu', '1989-03-02');
insert into Clients (FullName, Email, YearOfBirth) values ('Zabrina Ladloe', 'zladloer@comsenz.com', '1995-12-14');
insert into Clients (FullName, Email, YearOfBirth) values ('Robby Bohlin', 'rbohlins@unesco.org', '1989-09-16');
insert into Clients (FullName, Email, YearOfBirth) values ('Justine Hampshire', 'jhampshiret@mashable.com', '1996-10-15');
insert into Clients (FullName, Email, YearOfBirth) values ('Berny Hansod', 'bhansodu@netvibes.com', '1995-03-08');
insert into Clients (FullName, Email, YearOfBirth) values ('Nari Cridland', 'ncridlandv@aboutads.info', '1966-01-10');
insert into Clients (FullName, Email, YearOfBirth) values ('Willey Fraschetti', 'wfraschettiw@addtoany.com', '1990-02-07');
insert into Clients (FullName, Email, YearOfBirth) values ('Nola Krolman', 'nkrolmanx@etsy.com', '1972-03-30');
insert into Clients (FullName, Email, YearOfBirth) values ('Clemente Goare', 'cgoarey@google.es', '1971-10-13');
insert into Clients (FullName, Email, YearOfBirth) values ('Petra Sacher', 'psacherz@blinklist.com', '1985-07-29');
insert into Clients (FullName, Email, YearOfBirth) values ('Zachary Rowson', 'zrowson10@mediafire.com', '1968-01-10');
insert into Clients (FullName, Email, YearOfBirth) values ('Baxie Varvell', 'bvarvell11@whitehouse.gov', '1965-04-10');
insert into Clients (FullName, Email, YearOfBirth) values ('Laurent Whye', 'lwhye12@state.tx.us', '1982-12-27');
insert into Clients (FullName, Email, YearOfBirth) values ('Tallou Peddel', 'tpeddel13@elegantthemes.com', '1979-09-09');
insert into Clients (FullName, Email, YearOfBirth) values ('Randolf Klement', 'rklement14@ed.gov', '1997-01-17');
insert into Clients (FullName, Email, YearOfBirth) values ('Rolland Macy', 'rmacy15@smugmug.com', '1972-09-04');
insert into Clients (FullName, Email, YearOfBirth) values ('Gustaf Gostick', 'ggostick16@mediafire.com', '1982-02-18');
insert into Clients (FullName, Email, YearOfBirth) values ('Tadio Farrant', 'tfarrant17@salon.com', '1978-09-19');
insert into Clients (FullName, Email, YearOfBirth) values ('Harley Settle', 'hsettle18@angelfire.com', '1976-06-03');
insert into Clients (FullName, Email, YearOfBirth) values ('Armand Simkovich', 'asimkovich19@studiopress.com', '1993-05-08');
insert into Clients (FullName, Email, YearOfBirth) values ('Lorie Smallacombe', 'lsmallacombe1a@weebly.com', '1993-05-31');
insert into Clients (FullName, Email, YearOfBirth) values ('Tammy Deering', 'tdeering1b@smh.com.au', '1995-02-03');
insert into Clients (FullName, Email, YearOfBirth) values ('Helli Gregon', 'hgregon1c@weebly.com', '1984-07-06');
insert into Clients (FullName, Email, YearOfBirth) values ('Jonie Cawson', 'jcawson1d@miibeian.gov.cn', '1992-07-07');
insert into Clients (FullName, Email, YearOfBirth) values ('Bunnie Gleder', 'bgleder0@blogs.com', '2015-05-03');
insert into Clients (FullName, Email, YearOfBirth) values ('Trisha Huntall', 'thuntall1@soup.io', '2016-10-01');
insert into Clients (FullName, Email, YearOfBirth) values ('Land Fenwick', 'lfenwick2@cyberchimps.com', '2011-01-18');
insert into Clients (FullName, Email, YearOfBirth) values ('Victor Assender', 'vassender3@123-reg.co.uk', '2016-05-29');
insert into Clients (FullName, Email, YearOfBirth) values ('Richmond Shailer', 'rshailer4@digg.com', '2013-06-13');
insert into Clients (FullName, Email, YearOfBirth) values ('Karim Spinke', 'kspinke5@behance.net', '2014-12-11');
insert into Clients (FullName, Email, YearOfBirth) values ('Franky Catterell', 'fcatterell6@ocn.ne.jp', '2012-10-27');
insert into Clients (FullName, Email, YearOfBirth) values ('Marshall McKew', 'mmckew7@deliciousdays.com', '2010-07-16');
insert into Clients (FullName, Email, YearOfBirth) values ('Evelina Kinahan', 'ekinahan8@gov.uk', '2010-10-07');
insert into Clients (FullName, Email, YearOfBirth) values ('Wain Kynder', 'wkynder9@symantec.com', '2009-05-17');
														   
														   
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\1.jpg', SINGLE_BLOB) image);
insert into Images (Files) 
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\2.jpg', SINGLE_BLOB) image);
insert into Images (Files) 
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\3.jpg', SINGLE_BLOB) image);
insert into Images (Files) 
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\4.jpg', SINGLE_BLOB) image);
insert into Images (Files) 
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\5.jpg', SINGLE_BLOB) image); 
insert into Images (Files) 
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\6.jpg', SINGLE_BLOB) image);  
insert into Images (Files) 
(SELECT BulkColumn FROM OPENROWSET(BULK N'C:\ExamSql\7.jpg', SINGLE_BLOB) image);

 

insert into Events (Restriction, [Name], CategoriyId, [Description], ImageId) values (12, 'Concert Stoletiya',2, 'V cest yubileye Qubernatora .Vistupayut : Koncita, Faiq Agayev , Oleq Qazmanov i dr.', 2);
insert into Events (Restriction, [Name], CategoriyId, [Description], ImageId) values (6, 'Belie Medvedi', 4, 'Vistupayut professionalnie akrobati Tarzan i td. Jivotie : Medvedi,Tiqri,Obezyani i t.d', 6);
insert into Events (Restriction, [Name], CategoriyId, [Description], ImageId) values (14, 'Olimpiyskie iqri', 5, 'Letnie Olimpiyskie Iqri', 7);
insert into Events (Restriction, [Name], CategoriyId, [Description], ImageId) values (16,'Celovek Pauk', 7, 'Piter Parker obiknovenniy wkolnik.Odnajni on otpravilsya s klassom na Eekskursiyu,gde equ kusaet paukt.Cerez vremya on podveraetsa Mutacii', 4);
insert into Events (Restriction, [Name], CategoriyId, [Description], ImageId) values (16,'Otstupnik', 7, 'Otstupnik (The Departed) — amerikanskiy xudojestveniy film, kriminalniy dramaticeskiy triller', 4); 
  


 
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 8, 669, '2020-10-08 13:21:30', 1); 
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 4, 594, '2020-12-30 05:38:06', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 10, 495, '2021-07-25 00:59:54', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 8, 686, '2020-10-28 14:55:55', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 4, 352, '2022-04-30 19:09:01', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 5, 298, '2021-02-26 21:00:38', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 7, 912, '2021-09-19 21:44:39', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 9, 313, '2020-07-14 14:22:58', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 6, 127, '2021-01-30 02:34:43', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 2, 282, '2021-08-12 15:03:24', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (4, 6, 345, '2022-05-06 05:28:43', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 6, 452, '2021-07-03 21:45:29', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (4, 4, 407, '2021-09-29 05:01:54', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 2, 852, '2020-07-28 02:23:55', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 9, 516, '2022-01-23 13:13:48', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 6, 314, '2022-03-07 01:00:23', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 3, 927, '2022-05-18 03:26:12', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 3, 359, '2022-03-28 19:48:51', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 7, 191, '2022-03-01 11:52:37', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 2, 101, '2020-10-15 00:48:44', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 4, 627, '2021-11-10 00:21:39', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 8, 328, '2021-05-28 17:18:15', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 6, 921, '2022-04-09 04:24:52', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (4, 6, 432, '2021-12-21 22:35:54', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 10, 201, '2020-08-09 09:47:38', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 1, 824, '2022-04-17 13:55:41', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 8, 506, '2021-12-12 19:46:03', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 5, 522, '2021-03-08 22:35:11', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 1, 867, '2021-04-03 18:53:11', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 7, 532, '2021-11-16 05:41:43', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 10, 833, '2020-10-11 08:33:45', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 1, 484, '2021-06-26 11:06:28', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 3, 426, '2021-01-13 22:17:44', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 7, 593, '2020-06-22 04:06:26', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 2, 110, '2021-05-19 07:07:53', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 10, 810, '2021-04-10 11:16:15', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 1, 701, '2021-10-03 11:07:33', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 7, 555, '2021-08-10 09:58:36', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 9, 769, '2021-11-20 10:33:57', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 7, 563, '2021-09-20 19:08:19', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 9, 878, '2022-02-09 02:21:28', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (3, 4, 250, '2021-12-11 20:16:30', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 2, 710, '2021-02-26 23:40:25', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (4, 3, 959, '2021-07-13 19:53:09', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 1, 468, '2020-12-21 19:51:42', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (1, 4, 952, '2022-05-13 03:18:59', 1);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (4, 8, 747, '2020-10-19 09:05:30', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 2, 769, '2020-06-30 04:39:04', 2);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (5, 9, 371, '2022-02-13 02:01:50', 3);
insert into Schedules (EventId, ProvidenceId, CountTickets, [DateTime], DurationDay) values (2, 7, 939, '2021-05-23 07:30:01', 2);
 

insert into Sales (ScheduleId, CountTickets, ClientId) values (11, 4, 9);
insert into Sales (ScheduleId, CountTickets, ClientId) values (22, 3, 47);
insert into Sales (ScheduleId, CountTickets, ClientId) values (3, 1, 2);
insert into Sales (ScheduleId, CountTickets, ClientId) values (4, 4, 33);
insert into Sales (ScheduleId, CountTickets, ClientId) values (5, 5, 33);
insert into Sales (ScheduleId, CountTickets, ClientId) values (6, 4, 35);
insert into Sales (ScheduleId, CountTickets, ClientId) values (7, 5, 43);
insert into Sales (ScheduleId, CountTickets, ClientId) values (8, 5, 11);
insert into Sales (ScheduleId, CountTickets, ClientId) values (9, 1, 9);
insert into Sales (ScheduleId, CountTickets, ClientId) values (10, 3, 22);
insert into Sales (ScheduleId, CountTickets, ClientId) values (11, 1, 29);
insert into Sales (ScheduleId, CountTickets, ClientId) values (12, 2, 34);
insert into Sales (ScheduleId, CountTickets, ClientId) values (13, 1, 9);
insert into Sales (ScheduleId, CountTickets, ClientId) values (14, 5, 17);
insert into Sales (ScheduleId, CountTickets, ClientId) values (15, 4, 44);
insert into Sales (ScheduleId, CountTickets, ClientId) values (16, 5, 29);
insert into Sales (ScheduleId, CountTickets, ClientId) values (17, 5, 26);
insert into Sales (ScheduleId, CountTickets, ClientId) values (18, 3, 47);
insert into Sales (ScheduleId, CountTickets, ClientId) values (19, 3, 12);
insert into Sales (ScheduleId, CountTickets, ClientId) values (20, 5, 22);
insert into Sales (ScheduleId, CountTickets, ClientId) values (21, 3, 19);
insert into Sales (ScheduleId, CountTickets, ClientId) values (22, 3, 35);
insert into Sales (ScheduleId, CountTickets, ClientId) values (23, 4, 38);
insert into Sales (ScheduleId, CountTickets, ClientId) values (24, 4, 39);
insert into Sales (ScheduleId, CountTickets, ClientId) values (25, 5, 16);
insert into Sales (ScheduleId, CountTickets, ClientId) values (26, 2, 34);
insert into Sales (ScheduleId, CountTickets, ClientId) values (27, 1, 8);
insert into Sales (ScheduleId, CountTickets, ClientId) values (28, 2, 36);
insert into Sales (ScheduleId, CountTickets, ClientId) values (29, 5, 25);
insert into Sales (ScheduleId, CountTickets, ClientId) values (30, 5, 12);
insert into Sales (ScheduleId, CountTickets, ClientId) values (31, 3, 6);
insert into Sales (ScheduleId, CountTickets, ClientId) values (32, 2, 24);
insert into Sales (ScheduleId, CountTickets, ClientId) values (33, 2, 47);
insert into Sales (ScheduleId, CountTickets, ClientId) values (34, 4, 18);
insert into Sales (ScheduleId, CountTickets, ClientId) values (35, 4, 26);
insert into Sales (ScheduleId, CountTickets, ClientId) values (36, 2, 48);
insert into Sales (ScheduleId, CountTickets, ClientId) values (37, 5, 29);
insert into Sales (ScheduleId, CountTickets, ClientId) values (38, 3, 48);
insert into Sales (ScheduleId, CountTickets, ClientId) values (39, 4, 4);
insert into Sales (ScheduleId, CountTickets, ClientId) values (40, 1, 34);
insert into Sales (ScheduleId, CountTickets, ClientId) values (41, 5, 2);
insert into Sales (ScheduleId, CountTickets, ClientId) values (42, 3, 32);
insert into Sales (ScheduleId, CountTickets, ClientId) values (43, 2, 16);
insert into Sales (ScheduleId, CountTickets, ClientId) values (44, 4, 48);
insert into Sales (ScheduleId, CountTickets, ClientId) values (45, 2, 17);
insert into Sales (ScheduleId, CountTickets, ClientId) values (46, 3, 5);
insert into Sales (ScheduleId, CountTickets, ClientId) values (47, 1, 47);
insert into Sales (ScheduleId, CountTickets, ClientId) values (48, 5, 42);
insert into Sales (ScheduleId, CountTickets, ClientId) values (49, 4, 45);
insert into Sales (ScheduleId, CountTickets, ClientId) values (50, 3, 25);
insert into Sales (ScheduleId, CountTickets, ClientId) values (11,  5, 19);
insert into Sales (ScheduleId, CountTickets, ClientId) values (22,  2, 29);
insert into Sales (ScheduleId, CountTickets, ClientId) values (3,  1, 32);
insert into Sales (ScheduleId, CountTickets, ClientId) values (4,  4, 22);
insert into Sales (ScheduleId, CountTickets, ClientId) values (5,  3, 50);
insert into Sales (ScheduleId, CountTickets, ClientId) values (6,  4, 12);
insert into Sales (ScheduleId, CountTickets, ClientId) values (7,  4, 30);
insert into Sales (ScheduleId, CountTickets, ClientId) values (8,  2, 45);
insert into Sales (ScheduleId, CountTickets, ClientId) values (9,  5, 23);
insert into Sales (ScheduleId, CountTickets, ClientId) values (10, 1, 30);
insert into Sales (ScheduleId, CountTickets, ClientId) values (11,5, 36);
insert into Sales (ScheduleId, CountTickets, ClientId) values (12,4, 34);
insert into Sales (ScheduleId, CountTickets, ClientId) values (13,1, 45);
insert into Sales (ScheduleId, CountTickets, ClientId) values (14,4, 42);
insert into Sales (ScheduleId, CountTickets, ClientId) values (15,1, 19);
insert into Sales (ScheduleId, CountTickets, ClientId) values (16,2, 3);
insert into Sales (ScheduleId, CountTickets, ClientId) values (17,1, 43);
insert into Sales (ScheduleId, CountTickets, ClientId) values (18,2, 49);
insert into Sales (ScheduleId, CountTickets, ClientId) values (19,4, 18);
insert into Sales (ScheduleId, CountTickets, ClientId) values (20,4, 44);
insert into Sales (ScheduleId, CountTickets, ClientId) values (21,3, 4);
insert into Sales (ScheduleId, CountTickets, ClientId) values (22,4, 24);
insert into Sales (ScheduleId, CountTickets, ClientId) values (23,1, 39);
insert into Sales (ScheduleId, CountTickets, ClientId) values (24,3, 1);
insert into Sales (ScheduleId, CountTickets, ClientId) values (25,1, 27);
insert into Sales (ScheduleId, CountTickets, ClientId) values (26,4, 48);
insert into Sales (ScheduleId, CountTickets, ClientId) values (27,5, 14);
insert into Sales (ScheduleId, CountTickets, ClientId) values (28,1, 27);
insert into Sales (ScheduleId, CountTickets, ClientId) values (29,5, 4);
insert into Sales (ScheduleId, CountTickets, ClientId) values (30,5, 33);
insert into Sales (ScheduleId, CountTickets, ClientId) values (31,4, 6);
insert into Sales (ScheduleId, CountTickets, ClientId) values (32,4, 30);
insert into Sales (ScheduleId, CountTickets, ClientId) values (33,2, 34);
insert into Sales (ScheduleId, CountTickets, ClientId) values (34,2, 17);
insert into Sales (ScheduleId, CountTickets, ClientId) values (35,5, 21);
insert into Sales (ScheduleId, CountTickets, ClientId) values (36,5, 26);
insert into Sales (ScheduleId, CountTickets, ClientId) values (37,5, 1);
insert into Sales (ScheduleId, CountTickets, ClientId) values (38,1, 12);
insert into Sales (ScheduleId, CountTickets, ClientId) values (39,1, 16);
insert into Sales (ScheduleId, CountTickets, ClientId) values (40,3, 3);
insert into Sales (ScheduleId, CountTickets, ClientId) values (41,4, 42);
insert into Sales (ScheduleId, CountTickets, ClientId) values (42,5, 34);
insert into Sales (ScheduleId, CountTickets, ClientId) values (43,1, 1);
insert into Sales (ScheduleId, CountTickets, ClientId) values (44,1, 15);
insert into Sales (ScheduleId, CountTickets, ClientId) values (45,5, 36);
insert into Sales (ScheduleId, CountTickets, ClientId) values (46,1, 12);
insert into Sales (ScheduleId, CountTickets, ClientId) values (47,1, 13);
insert into Sales (ScheduleId, CountTickets, ClientId) values (48,2, 14);
insert into Sales (ScheduleId, CountTickets, ClientId) values (49,4, 31);
insert into Sales (ScheduleId, CountTickets, ClientId) values (1,495, 6);
insert into Sales (ScheduleId, CountTickets, ClientId) values (2,910, 3); 
